<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // Afrique (continent_id => 1)
            ['name' => 'Afrique du Sud', 'code' => 'ZA',  'flag' => 'flags/za.png', 'phone_code' => '+27', 'currency' => 'ZAR'],
            ['name' => 'Algérie', 'code' => 'DZ',  'flag' => 'flags/dz.png', 'phone_code' => '+213', 'currency' => 'DZD'],
            ['name' => 'Angola', 'code' => 'AO',  'flag' => 'flags/ao.png', 'phone_code' => '+244', 'currency' => 'AOA'],
            ['name' => 'Bénin', 'code' => 'BJ',  'flag' => 'flags/bj.png', 'phone_code' => '+229', 'currency' => 'XOF'],
            ['name' => 'Botswana', 'code' => 'BW',  'flag' => 'flags/bw.png', 'phone_code' => '+267', 'currency' => 'BWP'],
            ['name' => 'Burkina Faso', 'code' => 'BF',  'flag' => 'flags/bf.png', 'phone_code' => '+226', 'currency' => 'XOF'],
            ['name' => 'Burundi', 'code' => 'BI',  'flag' => 'flags/bi.png', 'phone_code' => '+257', 'currency' => 'BIF'],
            ['name' => 'Cameroun', 'code' => 'CM',  'flag' => 'flags/cm.png', 'phone_code' => '+237', 'currency' => 'XAF'],
            ['name' => 'Cap-Vert', 'code' => 'CV',  'flag' => 'flags/cv.png', 'phone_code' => '+238', 'currency' => 'CVE'],
            ['name' => 'Comores', 'code' => 'KM',  'flag' => 'flags/km.png', 'phone_code' => '+269', 'currency' => 'KMF'],
            ['name' => 'Congo', 'code' => 'CG',  'flag' => 'flags/cg.png', 'phone_code' => '+242', 'currency' => 'XAF'],
            ['name' => 'Congo (RDC)', 'code' => 'CD',  'flag' => 'flags/cd.png', 'phone_code' => '+243', 'currency' => 'CDF'],
            ['name' => 'Côte d\'Ivoire', 'code' => 'CI',  'flag' => 'flags/ci.png', 'phone_code' => '+225', 'currency' => 'XOF'],
            ['name' => 'Djibouti', 'code' => 'DJ',  'flag' => 'flags/dj.png', 'phone_code' => '+253', 'currency' => 'DJF'],
            ['name' => 'Égypte', 'code' => 'EG',  'flag' => 'flags/eg.png', 'phone_code' => '+20', 'currency' => 'EGP'],
            ['name' => 'Érythrée', 'code' => 'ER',  'flag' => 'flags/er.png', 'phone_code' => '+291', 'currency' => 'ERN'],
            ['name' => 'Eswatini', 'code' => 'SZ',  'flag' => 'flags/sz.png', 'phone_code' => '+268', 'currency' => 'SZL'],
            ['name' => 'Éthiopie', 'code' => 'ET',  'flag' => 'flags/et.png', 'phone_code' => '+251', 'currency' => 'ETB'],
            ['name' => 'Gabon', 'code' => 'GA',  'flag' => 'flags/ga.png', 'phone_code' => '+241', 'currency' => 'XAF'],
            ['name' => 'Gambie', 'code' => 'GM',  'flag' => 'flags/gm.png', 'phone_code' => '+220', 'currency' => 'GMD'],
            ['name' => 'Ghana', 'code' => 'GH',  'flag' => 'flags/gh.png', 'phone_code' => '+233', 'currency' => 'GHS'],
            ['name' => 'Guinée', 'code' => 'GN',  'flag' => 'flags/gn.png', 'phone_code' => '+224', 'currency' => 'GNF'],
            ['name' => 'Guinée-Bissau', 'code' => 'GW',  'flag' => 'flags/gw.png', 'phone_code' => '+245', 'currency' => 'XOF'],
            ['name' => 'Guinée équatoriale', 'code' => 'GQ',  'flag' => 'flags/gq.png', 'phone_code' => '+240', 'currency' => 'XAF'],
            ['name' => 'Kenya', 'code' => 'KE',  'flag' => 'flags/ke.png', 'phone_code' => '+254', 'currency' => 'KES'],
            ['name' => 'Lesotho', 'code' => 'LS',  'flag' => 'flags/ls.png', 'phone_code' => '+266', 'currency' => 'LSL'],
            ['name' => 'Liberia', 'code' => 'LR',  'flag' => 'flags/lr.png', 'phone_code' => '+231', 'currency' => 'LRD'],
            ['name' => 'Libye', 'code' => 'LY',  'flag' => 'flags/ly.png', 'phone_code' => '+218', 'currency' => 'LYD'],
            ['name' => 'Madagascar', 'code' => 'MG',  'flag' => 'flags/mg.png', 'phone_code' => '+261', 'currency' => 'MGA'],
            ['name' => 'Malawi', 'code' => 'MW',  'flag' => 'flags/mw.png', 'phone_code' => '+265', 'currency' => 'MWK'],
            ['name' => 'Mali', 'code' => 'ML',  'flag' => 'flags/ml.png', 'phone_code' => '+223', 'currency' => 'XOF'],
            ['name' => 'Maroc', 'code' => 'MA',  'flag' => 'flags/ma.png', 'phone_code' => '+212', 'currency' => 'MAD'],
            ['name' => 'Maurice', 'code' => 'MU',  'flag' => 'flags/mu.png', 'phone_code' => '+230', 'currency' => 'MUR'],
            ['name' => 'Mauritanie', 'code' => 'MR',  'flag' => 'flags/mr.png', 'phone_code' => '+222', 'currency' => 'MRU'],
            ['name' => 'Mozambique', 'code' => 'MZ',  'flag' => 'flags/mz.png', 'phone_code' => '+258', 'currency' => 'MZN'],
            ['name' => 'Namibie', 'code' => 'NA',  'flag' => 'flags/na.png', 'phone_code' => '+264', 'currency' => 'NAD'],
            ['name' => 'Niger', 'code' => 'NE',  'flag' => 'flags/ne.png', 'phone_code' => '+227', 'currency' => 'XOF'],
            ['name' => 'Nigeria', 'code' => 'NG',  'flag' => 'flags/ng.png', 'phone_code' => '+234', 'currency' => 'NGN'],
            ['name' => 'Ouganda', 'code' => 'UG',  'flag' => 'flags/ug.png', 'phone_code' => '+256', 'currency' => 'UGX'],
            ['name' => 'République centrafricaine', 'code' => 'CF',  'flag' => 'flags/cf.png', 'phone_code' => '+236', 'currency' => 'XAF'],
            ['name' => 'Rwanda', 'code' => 'RW',  'flag' => 'flags/rw.png', 'phone_code' => '+250', 'currency' => 'RWF'],
            ['name' => 'Sao Tomé-et-Principe', 'code' => 'ST',  'flag' => 'flags/st.png', 'phone_code' => '+239', 'currency' => 'STN'],
            ['name' => 'Sénégal', 'code' => 'SN',  'flag' => 'flags/sn.png', 'phone_code' => '+221', 'currency' => 'XOF'],
            ['name' => 'Seychelles', 'code' => 'SC',  'flag' => 'flags/sc.png', 'phone_code' => '+248', 'currency' => 'SCR'],
            ['name' => 'Sierra Leone', 'code' => 'SL',  'flag' => 'flags/sl.png', 'phone_code' => '+232', 'currency' => 'SLL'],
            ['name' => 'Somalie', 'code' => 'SO',  'flag' => 'flags/so.png', 'phone_code' => '+252', 'currency' => 'SOS'],
            ['name' => 'Soudan', 'code' => 'SD',  'flag' => 'flags/sd.png', 'phone_code' => '+249', 'currency' => 'SDG'],
            ['name' => 'Soudan du Sud', 'code' => 'SS',  'flag' => 'flags/ss.png', 'phone_code' => '+211', 'currency' => 'SSP'],
            ['name' => 'Tanzanie', 'code' => 'TZ',  'flag' => 'flags/tz.png', 'phone_code' => '+255', 'currency' => 'TZS'],
            ['name' => 'Tchad', 'code' => 'TD',  'flag' => 'flags/td.png', 'phone_code' => '+235', 'currency' => 'XAF'],
            ['name' => 'Togo', 'code' => 'TG',  'flag' => 'flags/tg.png', 'phone_code' => '+228', 'currency' => 'XOF'],
            ['name' => 'Tunisie', 'code' => 'TN',  'flag' => 'flags/tn.png', 'phone_code' => '+216', 'currency' => 'TND'],
            ['name' => 'Zambie', 'code' => 'ZM',  'flag' => 'flags/zm.png', 'phone_code' => '+260', 'currency' => 'ZMW'],
            ['name' => 'Zimbabwe', 'code' => 'ZW',  'flag' => 'flags/zw.png', 'phone_code' => '+263', 'currency' => 'ZWL'],

            // Asie (continent_id => 2)
            ['name' => 'Afghanistan', 'code' => 'AF',  'flag' => 'flags/af.png', 'phone_code' => '+93', 'currency' => 'AFN'],
            ['name' => 'Arabie saoudite', 'code' => 'SA',  'flag' => 'flags/sa.png', 'phone_code' => '+966', 'currency' => 'SAR'],
            ['name' => 'Arménie', 'code' => 'AM',  'flag' => 'flags/am.png', 'phone_code' => '+374', 'currency' => 'AMD'],
            ['name' => 'Azerbaïdjan', 'code' => 'AZ',  'flag' => 'flags/az.png', 'phone_code' => '+994', 'currency' => 'AZN'],
            ['name' => 'Bahreïn', 'code' => 'BH',  'flag' => 'flags/bh.png', 'phone_code' => '+973', 'currency' => 'BHD'],
            ['name' => 'Bangladesh', 'code' => 'BD',  'flag' => 'flags/bd.png', 'phone_code' => '+880', 'currency' => 'BDT'],
            ['name' => 'Bhoutan', 'code' => 'BT',  'flag' => 'flags/bt.png', 'phone_code' => '+975', 'currency' => 'BTN'],
            ['name' => 'Birmanie', 'code' => 'MM',  'flag' => 'flags/mm.png', 'phone_code' => '+95', 'currency' => 'MMK'],
            ['name' => 'Brunei', 'code' => 'BN',  'flag' => 'flags/bn.png', 'phone_code' => '+673', 'currency' => 'BND'],
            ['name' => 'Cambodge', 'code' => 'KH',  'flag' => 'flags/kh.png', 'phone_code' => '+855', 'currency' => 'KHR'],
            ['name' => 'Chine', 'code' => 'CN',  'flag' => 'flags/cn.png', 'phone_code' => '+86', 'currency' => 'CNY'],
            ['name' => 'Chypre', 'code' => 'CY',  'flag' => 'flags/cy.png', 'phone_code' => '+357', 'currency' => 'EUR'],
            ['name' => 'Corée du Nord', 'code' => 'KP',  'flag' => 'flags/kp.png', 'phone_code' => '+850', 'currency' => 'KPW'],
            ['name' => 'Corée du Sud', 'code' => 'KR',  'flag' => 'flags/kr.png', 'phone_code' => '+82', 'currency' => 'KRW'],
            ['name' => 'Émirats arabes unis', 'code' => 'AE',  'flag' => 'flags/ae.png', 'phone_code' => '+971', 'currency' => 'AED'],
            ['name' => 'Géorgie', 'code' => 'GE',  'flag' => 'flags/ge.png', 'phone_code' => '+995', 'currency' => 'GEL'],
            ['name' => 'Inde', 'code' => 'IN',  'flag' => 'flags/in.png', 'phone_code' => '+91', 'currency' => 'INR'],
            ['name' => 'Indonésie', 'code' => 'ID',  'flag' => 'flags/id.png', 'phone_code' => '+62', 'currency' => 'IDR'],
            ['name' => 'Irak', 'code' => 'IQ',  'flag' => 'flags/iq.png', 'phone_code' => '+964', 'currency' => 'IQD'],
            ['name' => 'Iran', 'code' => 'IR',  'flag' => 'flags/ir.png', 'phone_code' => '+98', 'currency' => 'IRR'],
            ['name' => 'Israël', 'code' => 'IL',  'flag' => 'flags/il.png', 'phone_code' => '+972', 'currency' => 'ILS'],
            ['name' => 'Japon', 'code' => 'JP',  'flag' => 'flags/jp.png', 'phone_code' => '+81', 'currency' => 'JPY'],
            ['name' => 'Jordanie', 'code' => 'JO',  'flag' => 'flags/jo.png', 'phone_code' => '+962', 'currency' => 'JOD'],
            ['name' => 'Kazakhstan', 'code' => 'KZ',  'flag' => 'flags/kz.png', 'phone_code' => '+7', 'currency' => 'KZT'],
            ['name' => 'Kirghizistan', 'code' => 'KG',  'flag' => 'flags/kg.png', 'phone_code' => '+996', 'currency' => 'KGS'],
            ['name' => 'Koweït', 'code' => 'KW',  'flag' => 'flags/kw.png', 'phone_code' => '+965', 'currency' => 'KWD'],
            ['name' => 'Laos', 'code' => 'LA',  'flag' => 'flags/la.png', 'phone_code' => '+856', 'currency' => 'LAK'],
            ['name' => 'Liban', 'code' => 'LB',  'flag' => 'flags/lb.png', 'phone_code' => '+961', 'currency' => 'LBP'],
            ['name' => 'Malaisie', 'code' => 'MY',  'flag' => 'flags/my.png', 'phone_code' => '+60', 'currency' => 'MYR'],
            ['name' => 'Maldives', 'code' => 'MV',  'flag' => 'flags/mv.png', 'phone_code' => '+960', 'currency' => 'MVR'],
            ['name' => 'Mongolie', 'code' => 'MN',  'flag' => 'flags/mn.png', 'phone_code' => '+976', 'currency' => 'MNT'],
            ['name' => 'Népal', 'code' => 'NP',  'flag' => 'flags/np.png', 'phone_code' => '+977', 'currency' => 'NPR'],
            ['name' => 'Oman', 'code' => 'OM',  'flag' => 'flags/om.png', 'phone_code' => '+968', 'currency' => 'OMR'],
            ['name' => 'Ouzbékistan', 'code' => 'UZ',  'flag' => 'flags/uz.png', 'phone_code' => '+998', 'currency' => 'UZS'],
            ['name' => 'Pakistan', 'code' => 'PK',  'flag' => 'flags/pk.png', 'phone_code' => '+92', 'currency' => 'PKR'],
            ['name' => 'Palestine', 'code' => 'PS',  'flag' => 'flags/ps.png', 'phone_code' => '+970', 'currency' => 'ILS'],
            ['name' => 'Philippines', 'code' => 'PH',  'flag' => 'flags/ph.png', 'phone_code' => '+63', 'currency' => 'PHP'],
            ['name' => 'Qatar', 'code' => 'QA',  'flag' => 'flags/qa.png', 'phone_code' => '+974', 'currency' => 'QAR'],
            ['name' => 'Singapour', 'code' => 'SG',  'flag' => 'flags/sg.png', 'phone_code' => '+65', 'currency' => 'SGD'],
            ['name' => 'Sri Lanka', 'code' => 'LK',  'flag' => 'flags/lk.png', 'phone_code' => '+94', 'currency' => 'LKR'],
            ['name' => 'Syrie', 'code' => 'SY',  'flag' => 'flags/sy.png', 'phone_code' => '+963', 'currency' => 'SYP'],
            ['name' => 'Tadjikistan', 'code' => 'TJ',  'flag' => 'flags/tj.png', 'phone_code' => '+992', 'currency' => 'TJS'],
            ['name' => 'Taïwan', 'code' => 'TW',  'flag' => 'flags/tw.png', 'phone_code' => '+886', 'currency' => 'TWD'],
            ['name' => 'Thaïlande', 'code' => 'TH',  'flag' => 'flags/th.png', 'phone_code' => '+66', 'currency' => 'THB'],
            ['name' => 'Timor oriental', 'code' => 'TL',  'flag' => 'flags/tl.png', 'phone_code' => '+670', 'currency' => 'USD'],
            ['name' => 'Turkménistan', 'code' => 'TM',  'flag' => 'flags/tm.png', 'phone_code' => '+993', 'currency' => 'TMT'],
            ['name' => 'Turquie', 'code' => 'TR',  'flag' => 'flags/tr.png', 'phone_code' => '+90', 'currency' => 'TRY'],
            ['name' => 'Vietnam', 'code' => 'VN',  'flag' => 'flags/vn.png', 'phone_code' => '+84', 'currency' => 'VND'],
            ['name' => 'Yémen', 'code' => 'YE',  'flag' => 'flags/ye.png', 'phone_code' => '+967', 'currency' => 'YER'],

            // Europe (continent_id => 3)
            ['name' => 'Albanie', 'code' => 'AL',  'flag' => 'flags/al.png', 'phone_code' => '+355', 'currency' => 'ALL'],
            ['name' => 'Allemagne', 'code' => 'DE',  'flag' => 'flags/de.png', 'phone_code' => '+49', 'currency' => 'EUR'],
            ['name' => 'Andorre', 'code' => 'AD',  'flag' => 'flags/ad.png', 'phone_code' => '+376', 'currency' => 'EUR'],
            ['name' => 'Autriche', 'code' => 'AT',  'flag' => 'flags/at.png', 'phone_code' => '+43', 'currency' => 'EUR'],
            ['name' => 'Belgique', 'code' => 'BE',  'flag' => 'flags/be.png', 'phone_code' => '+32', 'currency' => 'EUR'],
            ['name' => 'Biélorussie', 'code' => 'BY',  'flag' => 'flags/by.png', 'phone_code' => '+375', 'currency' => 'BYN'],
            ['name' => 'Bosnie-Herzégovine', 'code' => 'BA',  'flag' => 'flags/ba.png', 'phone_code' => '+387', 'currency' => 'BAM'],
            ['name' => 'Bulgarie', 'code' => 'BG',  'flag' => 'flags/bg.png', 'phone_code' => '+359', 'currency' => 'BGN'],
            ['name' => 'Croatie', 'code' => 'HR',  'flag' => 'flags/hr.png', 'phone_code' => '+385', 'currency' => 'EUR'],
            ['name' => 'Danemark', 'code' => 'DK',  'flag' => 'flags/dk.png', 'phone_code' => '+45', 'currency' => 'DKK'],
            ['name' => 'Espagne', 'code' => 'ES',  'flag' => 'flags/es.png', 'phone_code' => '+34', 'currency' => 'EUR'],
            ['name' => 'Estonie', 'code' => 'EE',  'flag' => 'flags/ee.png', 'phone_code' => '+372', 'currency' => 'EUR'],
            ['name' => 'Finlande', 'code' => 'FI',  'flag' => 'flags/fi.png', 'phone_code' => '+358', 'currency' => 'EUR'],
            ['name' => 'France', 'code' => 'FR',  'flag' => 'flags/fr.png', 'phone_code' => '+33', 'currency' => 'EUR'],
            ['name' => 'Grèce', 'code' => 'GR',  'flag' => 'flags/gr.png', 'phone_code' => '+30', 'currency' => 'EUR'],
            ['name' => 'Hongrie', 'code' => 'HU',  'flag' => 'flags/hu.png', 'phone_code' => '+36', 'currency' => 'HUF'],
            ['name' => 'Irlande', 'code' => 'IE',  'flag' => 'flags/ie.png', 'phone_code' => '+353', 'currency' => 'EUR'],
            ['name' => 'Islande', 'code' => 'IS',  'flag' => 'flags/is.png', 'phone_code' => '+354', 'currency' => 'ISK'],
            ['name' => 'Italie', 'code' => 'IT',  'flag' => 'flags/it.png', 'phone_code' => '+39', 'currency' => 'EUR'],
            ['name' => 'Kosovo', 'code' => 'XK',  'flag' => 'flags/xk.png', 'phone_code' => '+383', 'currency' => 'EUR'],
            ['name' => 'Lettonie', 'code' => 'LV',  'flag' => 'flags/lv.png', 'phone_code' => '+371', 'currency' => 'EUR'],
            ['name' => 'Liechtenstein', 'code' => 'LI',  'flag' => 'flags/li.png', 'phone_code' => '+423', 'currency' => 'CHF'],
            ['name' => 'Lituanie', 'code' => 'LT',  'flag' => 'flags/lt.png', 'phone_code' => '+370', 'currency' => 'EUR'],
            ['name' => 'Luxembourg', 'code' => 'LU',  'flag' => 'flags/lu.png', 'phone_code' => '+352', 'currency' => 'EUR'],
            ['name' => 'Macédoine du Nord', 'code' => 'MK',  'flag' => 'flags/mk.png', 'phone_code' => '+389', 'currency' => 'MKD'],
            ['name' => 'Malte', 'code' => 'MT',  'flag' => 'flags/mt.png', 'phone_code' => '+356', 'currency' => 'EUR'],
            ['name' => 'Moldavie', 'code' => 'MD',  'flag' => 'flags/md.png', 'phone_code' => '+373', 'currency' => 'MDL'],
            ['name' => 'Monaco', 'code' => 'MC',  'flag' => 'flags/mc.png', 'phone_code' => '+377', 'currency' => 'EUR'],
            ['name' => 'Monténégro', 'code' => 'ME',  'flag' => 'flags/me.png', 'phone_code' => '+382', 'currency' => 'EUR'],
            ['name' => 'Norvège', 'code' => 'NO',  'flag' => 'flags/no.png', 'phone_code' => '+47', 'currency' => 'NOK'],
            ['name' => 'Pays-Bas', 'code' => 'NL',  'flag' => 'flags/nl.png', 'phone_code' => '+31', 'currency' => 'EUR'],
            ['name' => 'Pologne', 'code' => 'PL',  'flag' => 'flags/pl.png', 'phone_code' => '+48', 'currency' => 'PLN'],
            ['name' => 'Portugal', 'code' => 'PT',  'flag' => 'flags/pt.png', 'phone_code' => '+351', 'currency' => 'EUR'],
            ['name' => 'République tchèque', 'code' => 'CZ',  'flag' => 'flags/cz.png', 'phone_code' => '+420', 'currency' => 'CZK'],
            ['name' => 'Roumanie', 'code' => 'RO',  'flag' => 'flags/ro.png', 'phone_code' => '+40', 'currency' => 'RON'],
            ['name' => 'Royaume-Uni', 'code' => 'GB',  'flag' => 'flags/gb.png', 'phone_code' => '+44', 'currency' => 'GBP'],
            ['name' => 'Russie', 'code' => 'RU',  'flag' => 'flags/ru.png', 'phone_code' => '+7', 'currency' => 'RUB'],
            ['name' => 'Saint-Marin', 'code' => 'SM',  'flag' => 'flags/sm.png', 'phone_code' => '+378', 'currency' => 'EUR'],
            ['name' => 'Serbie', 'code' => 'RS',  'flag' => 'flags/rs.png', 'phone_code' => '+381', 'currency' => 'RSD'],
            ['name' => 'Slovaquie', 'code' => 'SK',  'flag' => 'flags/sk.png', 'phone_code' => '+421', 'currency' => 'EUR'],
            ['name' => 'Slovénie', 'code' => 'SI',  'flag' => 'flags/si.png', 'phone_code' => '+386', 'currency' => 'EUR'],
            ['name' => 'Suède', 'code' => 'SE',  'flag' => 'flags/se.png', 'phone_code' => '+46', 'currency' => 'SEK'],
            ['name' => 'Suisse', 'code' => 'CH',  'flag' => 'flags/ch.png', 'phone_code' => '+41', 'currency' => 'CHF'],
            ['name' => 'Ukraine', 'code' => 'UA',  'flag' => 'flags/ua.png', 'phone_code' => '+380', 'currency' => 'UAH'],
            ['name' => 'Vatican', 'code' => 'VA',  'flag' => 'flags/va.png', 'phone_code' => '+39', 'currency' => 'EUR'],

            // Amérique du Nord (continent_id => 4)
            ['name' => 'Antigua-et-Barbuda', 'code' => 'AG',  'flag' => 'flags/ag.png', 'phone_code' => '+1', 'currency' => 'XCD'],
            ['name' => 'Bahamas', 'code' => 'BS',  'flag' => 'flags/bs.png', 'phone_code' => '+1', 'currency' => 'BSD'],
            ['name' => 'Barbade', 'code' => 'BB',  'flag' => 'flags/bb.png', 'phone_code' => '+1', 'currency' => 'BBD'],
            ['name' => 'Belize', 'code' => 'BZ',  'flag' => 'flags/bz.png', 'phone_code' => '+501', 'currency' => 'BZD'],
            ['name' => 'Canada', 'code' => 'CA',  'flag' => 'flags/ca.png', 'phone_code' => '+1', 'currency' => 'CAD'],
            ['name' => 'Costa Rica', 'code' => 'CR',  'flag' => 'flags/cr.png', 'phone_code' => '+506', 'currency' => 'CRC'],
            ['name' => 'Cuba', 'code' => 'CU',  'flag' => 'flags/cu.png', 'phone_code' => '+53', 'currency' => 'CUP'],
            ['name' => 'Dominique', 'code' => 'DM',  'flag' => 'flags/dm.png', 'phone_code' => '+1', 'currency' => 'XCD'],
            ['name' => 'États-Unis', 'code' => 'US',  'flag' => 'flags/us.png', 'phone_code' => '+1', 'currency' => 'USD'],
            ['name' => 'Grenade', 'code' => 'GD',  'flag' => 'flags/gd.png', 'phone_code' => '+1', 'currency' => 'XCD'],
            ['name' => 'Guatemala', 'code' => 'GT',  'flag' => 'flags/gt.png', 'phone_code' => '+502', 'currency' => 'GTQ'],
            ['name' => 'Haïti', 'code' => 'HT',  'flag' => 'flags/ht.png', 'phone_code' => '+509', 'currency' => 'HTG'],
            ['name' => 'Honduras', 'code' => 'HN',  'flag' => 'flags/hn.png', 'phone_code' => '+504', 'currency' => 'HNL'],
            ['name' => 'Jamaïque', 'code' => 'JM',  'flag' => 'flags/jm.png', 'phone_code' => '+1', 'currency' => 'JMD'],
            ['name' => 'Mexique', 'code' => 'MX',  'flag' => 'flags/mx.png', 'phone_code' => '+52', 'currency' => 'MXN'],
            ['name' => 'Nicaragua', 'code' => 'NI',  'flag' => 'flags/ni.png', 'phone_code' => '+505', 'currency' => 'NIO'],
            ['name' => 'Panama', 'code' => 'PA',  'flag' => 'flags/pa.png', 'phone_code' => '+507', 'currency' => 'PAB'],
            ['name' => 'République dominicaine', 'code' => 'DO',  'flag' => 'flags/do.png', 'phone_code' => '+1', 'currency' => 'DOP'],
            ['name' => 'Saint-Christophe-et-Niévès', 'code' => 'KN',  'flag' => 'flags/kn.png', 'phone_code' => '+1', 'currency' => 'XCD'],
            ['name' => 'Saint-Vincent-et-les-Grenadines', 'code' => 'VC',  'flag' => 'flags/vc.png', 'phone_code' => '+1', 'currency' => 'XCD'],
            ['name' => 'Sainte-Lucie', 'code' => 'LC',  'flag' => 'flags/lc.png', 'phone_code' => '+1', 'currency' => 'XCD'],
            ['name' => 'Salvador', 'code' => 'SV',  'flag' => 'flags/sv.png', 'phone_code' => '+503', 'currency' => 'USD'],
            ['name' => 'Trinité-et-Tobago', 'code' => 'TT',  'flag' => 'flags/tt.png', 'phone_code' => '+1', 'currency' => 'TTD'],

            // Amérique du Sud (continent_id => 5)
            ['name' => 'Argentine', 'code' => 'AR',  'flag' => 'flags/ar.png', 'phone_code' => '+54', 'currency' => 'ARS'],
            ['name' => 'Bolivie', 'code' => 'BO',  'flag' => 'flags/bo.png', 'phone_code' => '+591', 'currency' => 'BOB'],
            ['name' => 'Brésil', 'code' => 'BR',  'flag' => 'flags/br.png', 'phone_code' => '+55', 'currency' => 'BRL'],
            ['name' => 'Chili', 'code' => 'CL',  'flag' => 'flags/cl.png', 'phone_code' => '+56', 'currency' => 'CLP'],
            ['name' => 'Colombie', 'code' => 'CO',  'flag' => 'flags/co.png', 'phone_code' => '+57', 'currency' => 'COP'],
            ['name' => 'Équateur', 'code' => 'EC',  'flag' => 'flags/ec.png', 'phone_code' => '+593', 'currency' => 'USD'],
            ['name' => 'Guyana', 'code' => 'GY',  'flag' => 'flags/gy.png', 'phone_code' => '+592', 'currency' => 'GYD'],
            ['name' => 'Paraguay', 'code' => 'PY',  'flag' => 'flags/py.png', 'phone_code' => '+595', 'currency' => 'PYG'],
            ['name' => 'Pérou', 'code' => 'PE',  'flag' => 'flags/pe.png', 'phone_code' => '+51', 'currency' => 'PEN'],
            ['name' => 'Suriname', 'code' => 'SR',  'flag' => 'flags/sr.png', 'phone_code' => '+597', 'currency' => 'SRD'],
            ['name' => 'Uruguay', 'code' => 'UY',  'flag' => 'flags/uy.png', 'phone_code' => '+598', 'currency' => 'UYU'],
            ['name' => 'Venezuela', 'code' => 'VE',  'flag' => 'flags/ve.png', 'phone_code' => '+58', 'currency' => 'VES'],

            // Océanie (continent_id => 6)
            ['name' => 'Australie', 'code' => 'AU',  'flag' => 'flags/au.png', 'phone_code' => '+61', 'currency' => 'AUD'],
            ['name' => 'Fidji', 'code' => 'FJ',  'flag' => 'flags/fj.png', 'phone_code' => '+679', 'currency' => 'FJD'],
            ['name' => 'Îles Cook', 'code' => 'CK',  'flag' => 'flags/ck.png', 'phone_code' => '+682', 'currency' => 'NZD'],
            ['name' => 'Îles Marshall', 'code' => 'MH',  'flag' => 'flags/mh.png', 'phone_code' => '+692', 'currency' => 'USD'],
            ['name' => 'Îles Salomon', 'code' => 'SB',  'flag' => 'flags/sb.png', 'phone_code' => '+677', 'currency' => 'SBD'],
            ['name' => 'Kiribati', 'code' => 'KI',  'flag' => 'flags/ki.png', 'phone_code' => '+686', 'currency' => 'AUD'],
            ['name' => 'Micronésie', 'code' => 'FM',  'flag' => 'flags/fm.png', 'phone_code' => '+691', 'currency' => 'USD'],
            ['name' => 'Nauru', 'code' => 'NR',  'flag' => 'flags/nr.png', 'phone_code' => '+674', 'currency' => 'AUD'],
            ['name' => 'Niue', 'code' => 'NU',  'flag' => 'flags/nu.png', 'phone_code' => '+683', 'currency' => 'NZD'],
            ['name' => 'Nouvelle-Zélande', 'code' => 'NZ',  'flag' => 'flags/nz.png', 'phone_code' => '+64', 'currency' => 'NZD'],
            ['name' => 'Palaos', 'code' => 'PW',  'flag' => 'flags/pw.png', 'phone_code' => '+680', 'currency' => 'USD'],
            ['name' => 'Papouasie-Nouvelle-Guinée', 'code' => 'PG',  'flag' => 'flags/pg.png', 'phone_code' => '+675', 'currency' => 'PGK'],
            ['name' => 'Samoa', 'code' => 'WS',  'flag' => 'flags/ws.png', 'phone_code' => '+685', 'currency' => 'WST'],
            ['name' => 'Tonga', 'code' => 'TO',  'flag' => 'flags/to.png', 'phone_code' => '+676', 'currency' => 'TOP'],
            ['name' => 'Tuvalu', 'code' => 'TV',  'flag' => 'flags/tv.png', 'phone_code' => '+688', 'currency' => 'AUD'],
            ['name' => 'Vanuatu', 'code' => 'VU',  'flag' => 'flags/vu.png', 'phone_code' => '+678', 'currency' => 'VUV'],
        ];

        foreach ($countries as $country) {
            Country::create([
                'name' => $country['name'],
                'code' => $country['code'],
                'phone_code' => $country['phone_code'],
                'currency' => $country['currency'],
                'flag' => $country['flag'],
            ]);
        }
    }

}
